### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by imi-colt** [marwiss/IFC-graph#1]
NEO4J_USER neo4j
NEO4J_INITIAL_PASSWORD test1234
Could not establish connection.

Any ideas?

**Comment by marwiss** [comment]
A lot of possible reasons.

You cannot use the scipt until neo4j containers are running.

You can start checking in docker that neo4j containers are running without errors and ready for connections.

Normally it takes some time after launching docker compose up before neo4j containers and running you can use the script.

So maybe just wait some time before running the script.

**Comment by imi-colt** [comment]
Hi, I ran docker as you suggested and connected successfully but after executing the python script I ended with this error: 

neo4j.exceptions.clienterror: code: Neo.ClientError.Procedure.ProcedureNotFound
message: There is no procedure with the name „apoc.create.node“ registered for the database instance 😅 - any more suggestions?

**Comment by imi-colt** [comment]
I solved the issue, i ran also Neo4J Desktop with the same port, and it worked.
